apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py
  labels:
    app: hello-py
spec:
  selector:
    matchLabels:
      app: hello-py
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - name: hello-py
        image: 10.33.109.104/parallel-jobs/hello-py:latest
        ports:
        - containerPort: 5000
