apiVersion: v1
kind: Service
metadata:
  name: svc-api
  labels:
    run: svc-api
spec:
  type: NodePort
  ports:
  - name: tcp
    port: 5000
    nodePort: 30102
    protocol: TCP
  selector:
    name: api
