apiVersion: v1
kind: Service
metadata:
  name: svc-hello-nginx
  labels:
    app: svc-hello-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30103
    protocol: TCP
  selector:
    app: hello-nginx
