apiVersion: v1
kind: Service
metadata:
  name: svc-pallete
  labels:
    run: svc-pallete
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30103
    protocol: TCP
  selector:
    name: pallete
