apiVersion: v1
kind: Service
metadata:
  name: svc-scrapy
  labels:
    run: svc-scrapy
spec:
  type: NodePort
  ports:
  - name: tcp
    port: 6800
    nodePort: 30101
    protocol: TCP
  selector:
    name: scrapy
