apiVersion: v1
kind: Service
metadata:
  name: svc-pallete
  labels:
    app: svc-pallete
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    nodePort: 30101
    protocol: TCP
  selector:
    app: pallete
